### ISSUE TITLE
[BlueMap-Chat] Add an option to only show chat to authenticated users

### ISSUE THREAD

**Issue by globau** [Chicken/Auth#1]
First: BlueMap-Chat is awesome.

I have a feature request: I'd love it if the in-game chat was only visible to those who have logged into BlueMap (when `optional_authentication` is set to `true` of course).  That way I can make the map public, while keeping chat private.

Thanks!

**Comment by Chicken** [comment]
Great idea, I'll do that soonish.

**Comment by Chicken** [comment]
Added `read-auth` and `read-only` settings in https://github.com/Chicken/Auth/commit/e08b65daf3f35ca52d3b4acdf493427eb9264454 released in https://github.com/Chicken/Auth/releases/tag/bluemap-chat-v0.2.0
