### ISSUE TITLE
[Authentication] Sessions not persistant through restarts

### ISSUE THREAD

**Issue by Eatham532** [Chicken/Auth#6]
As title says. I am using the latest dev build version. It might be an issue with initializing the plugin.

**Comment by Chicken** [comment]
You mean that after a server restart everyone is logged out of the webapp?

**Comment by Eatham532** [comment]
Yeh. I will have to do more debugging though. I am using the Dev build version of Chat. But the published version of the auth plugins.

**Comment by Eatham532** [comment]
Ok, I think I know the issue. Correct me if I am wrong, but I think the sessions are IP locked. So going to another location will get you logged out.

**Comment by Chicken** [comment]
Oh yes that is indeed a feature. And apparently I never made a config option to disable it...
